<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TruckDiag.Plugins.Detroit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TruckDiag.Core\TruckDiag.Core.csproj" />
  </ItemGroup>

</Project>
